#!/usr/bin/env python3
"""Legacy board→frames slicer with hard aspect gate.

Production path is generate_storyboard_panels.py (Kie gpt-image-2 panels).
If {NNN}-board.panels.json exists, refuse — frames already come from panels.
Equal-grid crop must match media_aspect_ratio or exit.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

from asset_versions import (
    format_version,
    parse_version_prefix,
    set_frame_active_map,
)
from media_format import aspect_close, load_project_meta, resolve_cell_aspect

GRID_FOR_FRAMES = {
    3: (3, 1),  # cols x rows
    6: (3, 2),
    9: (3, 3),
}


def resolve_board(project: Path, board_version: int | None, explicit: Path | None) -> tuple[Path, int]:
    if explicit is not None:
        path = explicit if explicit.is_absolute() else (project / explicit)
        v = parse_version_prefix(path.name)
        if v is None:
            raise SystemExit(f"Board filename must start with NNN- prefix: {path.name}")
        return path, v

    sb_dir = project / "assets" / "storyboard"
    if board_version is not None:
        path = sb_dir / f"{format_version(board_version)}-board.png"
        if not path.is_file():
            raise SystemExit(f"Missing board: {path}")
        return path, board_version

    versions = []
    if sb_dir.is_dir():
        for p in sb_dir.glob("*-board.png"):
            v = parse_version_prefix(p.name)
            if v is not None:
                versions.append((v, p))
    if not versions:
        raise SystemExit(
            "No versioned board found. Expected assets/storyboard/001-board.png "
            "(use generate_storyboard_panels.py)."
        )
    v, path = max(versions, key=lambda t: t[0])
    return path, v


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Legacy slice only — prefer generate_storyboard_panels.py"
    )
    parser.add_argument("--project", required=True, type=Path)
    parser.add_argument("--frames", type=int, choices=[3, 6, 9], required=True)
    parser.add_argument("--input", type=Path, default=None, help="Versioned board path")
    parser.add_argument("--board-version", type=int, default=None, help="e.g. 2 for 002-board.png")
    parser.add_argument(
        "--only-cells",
        type=str,
        default=None,
        help="Comma list of 1-based cell indexes to write/update in active_map (default: all)",
    )
    parser.add_argument("--gutter", type=int, default=2)
    parser.add_argument(
        "--replace-active-map",
        action="store_true",
        help="Replace entire active_map instead of merging selected cells",
    )
    args = parser.parse_args()

    project = args.project.resolve()
    board, board_ver = resolve_board(project, args.board_version, args.input)
    ver = format_version(board_ver)

    panels_meta = project / "assets" / "storyboard" / f"{ver}-board.panels.json"
    if panels_meta.is_file():
        raise SystemExit(
            f"{panels_meta.name} exists — frames were generated by "
            "generate_storyboard_panels.py. Do not re-slice the stitched board "
            "(gutters shrink panels). Use assets/frames/{ver}-frame-*.png as-is."
        )

    meta = load_project_meta(project)
    cell_aspect = resolve_cell_aspect(None, meta)

    cols, rows = GRID_FOR_FRAMES[args.frames]
    out_dir = project / "assets" / "frames"
    out_dir.mkdir(parents=True, exist_ok=True)

    image = Image.open(board).convert("RGB")
    width, height = image.size
    cell_w = width // cols
    cell_h = height // rows
    gutter = max(args.gutter, 0)

    if args.only_cells:
        cells = {int(x.strip()) for x in args.only_cells.split(",") if x.strip()}
    else:
        cells = set(range(1, args.frames + 1))

    active_map: dict[str, str] = {}
    for i in range(args.frames):
        cell_idx = i + 1
        if cell_idx not in cells:
            continue
        col = i % cols
        row = i // cols
        left = col * cell_w + gutter
        upper = row * cell_h + gutter
        right = (col + 1) * cell_w - gutter
        lower = (row + 1) * cell_h - gutter
        cell = image.crop((left, upper, right, lower))
        cw, ch = cell.size
        if not aspect_close(cw, ch, cell_aspect):
            raise SystemExit(
                f"Sliced cell {cell_idx} is {cw}x{ch} (~{cw / ch:.4f}), "
                f"expected media_aspect_ratio {cell_aspect}. "
                "Use generate_storyboard_panels.py (Kie gpt-image-2) instead of board slice."
            )
        dest = out_dir / f"{ver}-frame-{cell_idx:02d}.png"
        cell.save(dest)
        rel = str(dest.relative_to(project)).replace("\\", "/")
        active_map[str(cell_idx)] = rel
        print(dest)

    set_frame_active_map(project, active_map, merge=not args.replace_active_map)
    print(f"board_version={ver} cells={sorted(cells)}")


if __name__ == "__main__":
    main()
